### ISSUE TITLE
Use arrow keys to switch between Yes / No with `toggle`

### ISSUE THREAD

**Issue by uncenter** [fabiospampinato/prask#2]

**Comment by fabiospampinato** [comment]
Which arrow keys? Left and Right should be handled already. I guess Up and Down could be handled too 🤔

**Comment by fabiospampinato** [comment]
v1.5.3 handles Up and Down also.

Let me know if that doesn't fix the problem and I'll reopen.

**Comment by fabiospampinato** [comment]
Fixed in v2.
